import { Category } from '../models/category.model';

export const CATEGORIES: Category[] = [
  {
    name: 'UMKM',
    image: './images/documentation/Categories=Nextjs.svg',
    description: 'Usaha Mikro, Kecil, dan Menengah',
    category: 'UMKM',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Regulasi',
    image: './images/documentation/Categories=React.svg',
    description: 'Perubahan dan aturan pajak terbaru',
    category: 'Regulasi',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Startup',
    image: './images/documentation/Categories=Tailwind.svg',
    description: 'Pajak dan akuntansi untuk startup',
    category: 'Startup',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Pribadi',
    image: './images/documentation/Categories=Typescript.svg',
    description: 'Pajak untuk individu dan pribadi',
    category: 'Pribadi',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Freelancer',
    image: './images/documentation/Categories=React.svg',
    description: 'Pajak untuk freelancer',
    category: 'Freelancer',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Internasional',
    image: './images/documentation/Categories=Nextjs.svg',
    description: 'Pajak bisnis internasional',
    category: 'Internasional',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Audit',
    image: './images/documentation/Categories=Tailwind.svg',
    description: 'Audit dan pemeriksaan pajak',
    category: 'Audit',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Digital',
    image: './images/documentation/Categories=Typescript.svg',
    description: 'Pajak ekonomi digital',
    category: 'Digital',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Manajemen',
    image: './images/documentation/Categories=React.svg',
    description: 'Manajemen pajak perusahaan',
    category: 'Manajemen',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Properti',
    image: './images/documentation/Categories=Nextjs.svg',
    description: 'Pajak properti dan real estate',
    category: 'Properti',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Transportasi',
    image: './images/documentation/Categories=Tailwind.svg',
    description: 'Pajak transportasi',
    category: 'Transportasi',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Warisan',
    image: './images/documentation/Categories=Typescript.svg',
    description: 'Pajak warisan dan hibah',
    category: 'Warisan',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Kreatif',
    image: './images/documentation/Categories=React.svg',
    description: 'Pajak industri kreatif',
    category: 'Kreatif',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'PPh Orang Pribadi',
    image: './images/documentation/Categories=React.svg',
    description: 'Pajak Penghasilan untuk individu',
    category: 'Pribadi',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'PPh Badan',
    image: './images/documentation/Categories=Nextjs.svg',
    description: 'Pajak Penghasilan untuk perusahaan',
    category: 'Startup',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'PPN',
    image: './images/documentation/Categories=Tailwind.svg',
    description: 'Pajak Pertambahan Nilai',
    category: 'Umum',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'PBB',
    image: './images/documentation/Categories=Typescript.svg',
    description: 'Pajak Bumi dan Bangunan',
    category: 'Properti',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Bea Materai',
    image: './images/documentation/Categories=React.svg',
    description: 'Pajak atas dokumen tertentu',
    category: 'Dokumen',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Pajak Kendaraan',
    image: './images/documentation/Categories=Tailwind.svg',
    description: 'Pajak atas kendaraan bermotor',
    category: 'Transportasi',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Pajak Ekspor-Impor',
    image: './images/documentation/Categories=Typescript.svg',
    description: 'Pajak atas kegiatan ekspor dan impor',
    category: 'Internasional',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Pajak Hiburan',
    image: './images/documentation/Categories=React.svg',
    description: 'Pajak atas jasa hiburan',
    category: 'Kreatif',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Pajak Hotel & Restoran',
    image: './images/documentation/Categories=Tailwind.svg',
    description: 'Pajak atas jasa hotel dan restoran',
    category: 'Properti',
    categoryClass: 'bg-malibu-purple',
  },
  {
    name: 'Pajak Rokok',
    image: './images/documentation/Categories=Typescript.svg',
    description: 'Pajak atas produk rokok',
    category: 'Kesehatan',
    categoryClass: 'bg-malibu-purple',
  },
];
